### ISSUE TITLE
minified css file name - always hash value appended

### ISSUE THREAD

**Issue by tommaton** [justeat/gulp-build-fozzie#99]
Hi All,

I'm not sure if this is a bug or whether I'm doing something wrong but when I try to do a production build I'm always getting a hash value at the end of the minified css file instead of style.min.css.

I've noticed js has an option `applyRevision`

But the CSS doesn't and always applies a revision hash number to the end, is there a way to disable this?

I see in the tasks for scripts there is 
```
.pipe(gulpif(applyRevision,
	rev()
))
```
But in the CSS tasks it always revisions
```
.pipe(rev())
```

Thanks,
Tom

**Comment by DamianMullins** [comment]
Looks like something we should update so that it behaves in a consistent way with the JS build. 

It might make sense to move `applyRevision` out of the `js` object so that it can be applied by setting a single value.

**Comment by tommaton** [comment]
From my perspective, that would be better solution. 

Either `applyRevision` to both or none at all.
